# Generated by Django 5.2 on 2026-07-05 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delay_from', models.DateTimeField()),
                ('delay_upto', models.DateTimeField()),
                ('delay_duration', models.DurationField()),
                ('delay_desc', models.TextField()),
                ('entered_by', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.agency')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.equipment')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.shop')),
                ('sub_equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.subequipment')),
            ],
        ),
    ]
