# Generated by Django 5.2 on 2026-07-10 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delays', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='delay',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='delay',
            old_name='sub_equipment',
            new_name='subequipment',
        ),
        migrations.AddField(
            model_name='delay',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='delay',
            name='entered_by',
            field=models.CharField(max_length=100),
        ),
    ]
