# Generated by Django 5.2 on 2026-07-11 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delays', '0002_rename_timestamp_delay_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='delay',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
