# Generated by Django 5.2 on 2026-07-11 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delays', '0003_delay_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delay',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
    ]
