# Generated by Django 5.2 on 2026-07-12 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delays', '0004_alter_delay_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='delay',
            name='remarks',
            field=models.TextField(blank=True, default=''),
        ),
    ]
