# Generated by Django 5.2 on 2026-07-12 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delays', '0005_delay_remarks'),
    ]

    operations = [
        migrations.CreateModel(
            name='DelayHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('user', models.CharField(max_length=50)),
                ('remarks', models.TextField(blank=True, default='')),
                ('action_date', models.DateTimeField(auto_now_add=True)),
                ('delay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delays.delay')),
            ],
        ),
    ]
