# Generated by Django 5.2 on 2026-07-18 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_department'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
